### ISSUE TITLE
Добавить возможность посылать POST запросы, для подготовки сайта для тестирования.

### ISSUE THREAD

**Issue by dimazaicev88** [tachometer-int/tachometer-extractor#19]
Нужно будет отправлять POST запрос для заполнения корзины, для этого нужно будет отправить ID пользователя и список товаров,

**Comment by Ser-Gen** [comment]
По-идее, связана с #16, там так же данные приходится отправлять перед началом измерений. Можно объединить обе возможности.
В модуль нужно будет передавать объект с набором путей и полей с данными, которые будут рассылаться при первой загрузке.

```
post="[{
	'path': '%url%',
	'data': [
		'%field%': '%value%'
	],
	'match': '' // в ответе должна быть эта строка, для проверки успешности запроса
}]"
```

**Comment by dimazaicev88** [comment]
Да

**Comment by Ser-Gen** [comment]
Сделано в [1.3.0](https://github.com/tachometer-int/tachometer-extractor/releases/tag/1.3.0).
Вместо захардкоживания отправки именно пост-запроса реализовано поле для выполнения произвольной ДжС-функции, которая уже может отправлять запросы и делать всякое.
